channels:
- conda-forge
dependencies:
- python=3.10.17
- pip<=21.3.1
- pip:
  - mlflow==2.22.0
  - backports-tempfile==1.0
  - cffi==1.17.1
  - cloudpickle==2.2.1
  - jaraco-collections==5.1.0
  - lightgbm==4.3.0
  - matplotlib==3.5.3
  - numpy==1.22.4
  - pandas==1.5.3
  - psutil==5.8.0
  - pyarrow==20.0.0
  - scikit-learn==1.5.2
name: mlflow-env
